export const MOCK_TECHNICIANS = [
  { id: 1, name: 'Marco Ferretti' },
  { id: 2, name: 'Giulia Santoro' },
  { id: 3, name: 'Luca Bianchi' },
  { id: 4, name: 'Sara Conti' },
]

export const MOCK_STATIONS = [
  { id: 1, name: 'Pordenone Centro' },
  { id: 2, name: 'Stazione PN-03' },
  { id: 3, name: 'Rete 5' },
  { id: 4, name: 'Stazione Nord' },
  { id: 5, name: 'Piazza Cavour' },
]

export const MOCK_VEHICLES = [
  { id: 1, license_plate: 'BIKE-3421' },
  { id: 2, license_plate: 'BIKE-7823' },
  { id: 3, license_plate: 'SCOOT-1192' },
  { id: 4, license_plate: 'SCOOT-4455' },
  { id: 5, license_plate: 'AUTO-GH291AB' },
  { id: 6, license_plate: 'UTENTE #123' },
]

export const MOCK_TICKETS = [
  {
    id: 1,
    status: 'Aperti',
    vehicle: 'BIKE-3421',
    title: 'Guasto freno anteriore',
    station: 'Stazione PN-03',
    priority: 'Alta',
    technician: 'Non assegnato',
    notes: [],
    createdAt: 'Oggi 08:12',
  },
  {
    id: 2,
    status: 'Aperti',
    vehicle: 'UTENTE #123',
    title: 'Pagamento rifiutato app',
    station: '',
    priority: 'Alta',
    technician: 'Giulia Santoro',
    notes: [
      { id: 1, text: 'Cliente ha contattato il supporto via email. Problemi con carta di credito scaduta.' },
    ],
    createdAt: 'Oggi 10:30',
  },
  {
    id: 3,
    status: 'Aperti',
    vehicle: 'SCOOT-4455',
    title: 'Blocco elettronico base di ricarica',
    station: 'Rete 5',
    priority: 'Media',
    technician: 'Marco Ferretti',
    notes: [],
    createdAt: 'Oggi 17:45',
  },
  {
    id: 4,
    status: 'In Corso',
    vehicle: 'BIKE-7823',
    title: 'Sostituzione pneumatico posteriore',
    station: 'Pordenone Centro',
    priority: 'Media',
    technician: 'Luca Bianchi',
    notes: [
      { id: 1, text: 'Recuperato il veicolo in stazione. Gomma completamente sgonfia, presenza di chiodo.' },
      { id: 2, text: 'Ordinata nuova camera d\'aria, attesa consegna domani mattina.' },
    ],
    createdAt: 'Ieri 14:20',
  },
  {
    id: 5,
    status: 'In Corso',
    vehicle: 'AUTO-GH291AB',
    title: 'Batteria scarica fuori area',
    station: 'Stazione Nord',
    priority: 'Alta',
    technician: 'Sara Conti',
    notes: [
      { id: 1, text: 'Veicolo localizzato a 3km dalla stazione più vicina. Inviato tecnico sul posto.' },
    ],
    createdAt: 'Ieri 09:00',
  },
  {
    id: 6,
    status: 'In Corso',
    vehicle: 'SCOOT-1192',
    title: 'Aggiornamento firmware IoT',
    station: 'Piazza Cavour',
    priority: 'Bassa',
    technician: 'Marco Ferretti',
    notes: [],
    createdAt: '3 giorni fa',
  },
  {
    id: 7,
    status: 'Chiusi',
    vehicle: 'BIKE-3421',
    title: 'Calibrazione sensore pedalata',
    station: 'Pordenone Centro',
    priority: 'Bassa',
    technician: 'Luca Bianchi',
    notes: [
      { id: 1, text: 'Intervento completato. Sensore ricalibrato, test superato.' },
    ],
    createdAt: '5 giorni fa',
  },
  {
    id: 8,
    status: 'Chiusi',
    vehicle: 'AUTO-GH291AB',
    title: 'Danni da vandalismo sportello',
    station: 'Stazione PN-03',
    priority: 'Alta',
    technician: 'Sara Conti',
    notes: [
      { id: 1, text: 'Sportello sinistro danneggiato. Presentata denuncia e avviata pratica assicurativa.' },
      { id: 2, text: 'Veicolo riparato presso carrozzeria convenzionata. Riconsegnato in stazione.' },
    ],
    createdAt: '1 settimana fa',
  },
  {
    id: 9,
    status: 'Chiusi',
    vehicle: 'SCOOT-4455',
    title: 'Sostituzione manopole consumate',
    station: 'Rete 5',
    priority: 'Bassa',
    technician: 'Giulia Santoro',
    notes: [
      { id: 1, text: 'Manopole sostituite con nuove. Intervento rapido, 15 minuti.' },
    ],
    createdAt: '2 settimane fa',
  },
]